inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - "config/initializers/devise.rb"

# Specs are inherently long; relax block & example length there.
RSpec/ExampleLength:
  Max: 20
RSpec/MultipleExpectations:
  Max: 5
RSpec/NestedGroups:
  Max: 4
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*"
